name: pokepedia
description: "Flutter Challenge"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  animate_do: ^3.3.4
  go_router: ^14.0.2
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_app.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#d81d17"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon_app.png
  fonts:
    - family: Pokefont
      fonts:
        - asset: assets/fonts/pokefont.ttf
